
## Generated at 2025-Feb-21 10:02

version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:2.20.3
    container_name: portainer
    restart: always
    ports:
      - 15200:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home1/_dockers/portainer:/data
    command: --admin-password $$2y$$05$$dq89HNAUy1U6Qmti8kf/Y.AvsGeGc3fao4FfbrYfu285pgjEUt3di
   
  grafana:
      image: grafana/grafana:11.1.4
      container_name: grafana
      restart: always
      hostname: 'grafana.demovl.ucoip.pt'
      ports:
        - 15210:3000
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        #- GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
        - GF_SERVER_SERVE_FROM_SUB_PATH=true
      volumes:
        - grafana_storage:/var/lib/grafana

  gitlab:
    image: gitlab/gitlab-ce:17.3.7-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.demovl.ucoip.pt'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.demovl.ucoip.pt'
        nginx['listen_https'] = false 
        nginx['redirect_http_to_https'] = false 
        nginx['listen_port'] = 8181        
        # Gitlab root password
        gitlab_rails['initial_root_password']='R0laBill#'
        # LDAP configuration
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_label'] = 'LDAP'
        gitlab_rails['ldap_host'] = '192.168.225.254'
        gitlab_rails['ldap_port'] = 389
        gitlab_rails['ldap_uid'] = 'uid'
        gitlab_rails['ldap_method'] = 'plain' # 'ssl' or 'plain'
        gitlab_rails['ldap_bind_dn'] = 'cn=reader,dc=demovl,dc=ucoip,dc=pt'
        gitlab_rails['ldap_password'] = '56411e7b7ee533db1ebaadd218a485e2'
        gitlab_rails['ldap_allow_username_or_email_login'] = true
        gitlab_rails['ldap_base'] = 'dc=demovl,dc=ucoip,dc=pt'        
    ports:
      - '15220:8181'
      - '15221:443'
      - '15222:22'
    volumes:
      - gitlab-install:/etc/gitlab 
      - gitlab-logs:/var/log/gitlab 
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'

  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: wekanteam/wekan:v7.59
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 15230:8080
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      #- ROOT_URL=http://localhost
      - ROOT_URL=https://wekan.demovl.ucoip.pt/
      - MAIL_URL=smtp://192.168.225.254:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@domain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
      - DEFAULT_AUTHENTICATION_METHOD=ldap
      - LDAP_ENABLE=true
      - LDAP_PORT=389
      - LDAP_HOST=192.168.225.254
      - LDAP_USER_AUTHENTICATION=true
      - LDAP_USER_AUTHENTICATION_FIELD=uid
      - LDAP_BASEDN=ou=Users,dc=demovl,dc=ucoip,dc=pt
      - LDAP_RECONNECT=true
      - LDAP_AUTHENTIFICATION=true
      - LDAP_AUTHENTIFICATION_USERDN=cn=reader,dc=demovl,dc=ucoip,dc=pt
      - LDAP_AUTHENTIFICATION_PASSWORD=56411e7b7ee533db1ebaadd218a485e2
      - LDAP_LOG_ENABLED=true
      - LDAP_ENCRYPTION=false
      - LDAP_USER_SEARCH_FILTER=(&(objectClass=inetOrgPerson))
      - LDAP_USER_SEARCH_SCOPE=one
      - LDAP_USER_SEARCH_FIELD=uid
      - LDAP_USERNAME_FIELD=uid
      - LDAP_FULLNAME_FIELD=cn
      - LDAP_EMAIL_FIELD=mail
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw


  outline:
    image: outlinewiki/outline:0.79.1
    container_name: outline
    environment:
      PGSSLMODE: disable
      DATABASE_URL: postgres://outline:537903729623336c44511ba9aca3ff57@postgres/outline
      REDIS_URL: redis://redis:6379
      SECRET_KEY: 87cc22cc7e856bdd4d51d42a1498570c9c2e5140135f51267b06c1fce864299f
      UTILS_SECRET: 6052a189ebe0690b967d6116be2df0ec6d58d59a029bbc12a59c5b135e738b02
      URL: https://outline.demovl.ucoip.pt/
      FORCE_HTTPS: false
    ports:
      - "15240:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14.13-bookworm
    container_name: outline-postgres-db
    environment:
      POSTGRES_USER: outline
      POSTGRES_PASSWORD: 537903729623336c44511ba9aca3ff57
      POSTGRES_DB: outline
    volumes:
      - outline-db-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.14-bookworm
    container_name: outline-redis-db
    volumes:
      - outline-redis-data:/data


volumes:
  grafana_storage: {}
  gitlab-install: {}
  gitlab-logs: {}
  gitlab-data: {}
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local  
  outline-db-data:
  outline-redis-data:


networks:
  wekan-tier:
    driver: bridge
  