services:
# KEYCLOAK
  keycloak:
    image: keycloak/keycloak:26.0
    networks:
      - ipbrick-v8
    container_name: keycloak_server
    environment:
      PROXY_ADDRESS_FORWARDING: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: wkhuneTBF3F5gMUrtDaKs9Xe
      KC_TRANSACTION_XA_ENABLED: false  # Melhor desempenho no PostgreSQL
      KC_BOOTSTRAP_ADMIN_USERNAME: admin                                          # KEYCLOAK_USERADMIN
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin                                          # KEYCLOAK_PASSADMIN
      KC_LOG_LEVEL: DEBUG
      # --------------- IMPORT ---------------
      IMPORT_SECRET_KEY: "PkIjqEKDZIJNtBFfln21SH9cHKyTYl80"                       # KEYCLOAK_IMPORT_SECRET
      IMPORT_BIND_CREDENTIAL: "15ac98720befec1d3f635426ccf15868"                  # KEYCLOAK_BIND_CREDENTIAL
      IMPORT_LDAP_IP: "ldap://62.28.182.152"                                      # KEYCLOAK_IMPORT_LDAP
      IMPORT_BIND_DN: "cn=Reader,dc=moreit,dc=ucoip,dc=pt"                        # KEYCLOAK_BIND_DN
      IMPORT_USERS_DN: "ou=users,dc=moreit,dc=ucoip,dc=pt"                        # KEYCLOAK_IMPORT_USERS_DN
    command: >
      start --import-realm
      --proxy=edge
      --hostname="https://keycloak.moreit.ucoip.pt"
      --http-enabled=true
      --spi-cookie-same-site=None
    ports:
    - "15380:8080"                                                                # KEYCLOAK_PORT_80
    - "15343:8443"                                                                # KEYCLOAK_PORT_443
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/imports:/opt/keycloak/data/import
    depends_on:
      - postgres
    restart: always

  # OUTLINE
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    networks:
      - ipbrick-v8
    container_name: outline_server
    environment:
      NODE_ENV: production                                                        # OUTLINE_MODE
      UTILS_SECRET: bba0b0f57a3e8c26d95b4a897905b5f6e5cb7f9299f6f3f6c0214e9fa8b957a6             # OUTLINE_UTILS_SECRET
      SECRET_KEY: 32233a2ec875682c31ec1dd7a3fd875c6c403a6f03f670af1a99ee84800f416b               # OUTLINE_SECRECT_KEY
      DATABASE_URL: postgres://admin:wkhuneTBF3F5gMUrtDaKs9Xe@postgres:5432/outline_db      # OUTLINE_POSTGRES_CONECTION
      DATABASE_CONNECTION_POOL_MIN:
      DATABASE_CONNECTION_POOL_MAX:
      PGSSLMODE: disable
      REDIS_URL: redis://redis:6379                                               # OUTLINE_REDIS
      URL: "https://outline.moreit.ucoip.pt"                                      # OUTLINE_URL
      PORT: 3000                                                                  # OUTLINE_PORT
      # Keycloak OAuth
      OIDC_CLIENT_ID: outline                                                     # OUTLINE_CLIENT_ID
      OIDC_CLIENT_SECRET: "PkIjqEKDZIJNtBFfln21SH9cHKyTYl80"                      # OUTLINE_CLIENT_SECRET
      OIDC_AUTH_URI: http://keycloak.moreit.ucoip.pt:15380/realms/moreit_realm/protocol/openid-connect/auth
      OIDC_TOKEN_URI: http://keycloak.moreit.ucoip.pt:15380/realms/moreit_realm/protocol/openid-connect/token
      OIDC_USERINFO_URI: http://keycloak.moreit.ucoip.pt:15380/realms/moreit_realm/protocol/openid-connect/userinfo
      OIDC_LOGOUT_URL: http://keycloak.moreit.ucoip.pt:15380/realms/moreit_realm/protocol/openid-connect/logout
      OIDC_REDIRECT_URI: https://outline.moreit.ucoip.ptallback
      FORCE_HTTPS: true
      TRUST_PROXY: true
      WEB_CONCURRENCY: 1
      DEBUG: http
      LOG_LEVEL: info
      DEFAULT_LANGUAGE: en_US
      RATE_LIMITER_ENABLED: true
      RATE_LIMITER_REQUESTS: 1000
      RATE_LIMITER_DURATION_WINDOW: 60
      DEVELOPMENT_UNSAFE_INLINE_CSP: false
      # Local File Storage
      FILE_STORAGE: local
      FILE_STORAGE_UPLOAD_MAX_SIZE: 52428800 #50MB
      FILE_STORAGE_IMPORT_MAX_SIZE: 5120000
    ports:
      - "15430:3000"
    depends_on:
      - postgres
      - redis
      - keycloak
    restart: always

  # POSTGRES
  postgres:
    image: postgres:12.22
    container_name: postgres_server
    ports:
      - "5432:5432"
    networks:
      - ipbrick-v8
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: wkhuneTBF3F5gMUrtDaKs9Xe
      POSTGRES_DB: postgres
    restart: always

  redis:
    image: redis:7.4
    container_name: outline_redis
    ports:
      - "6379:6379"
    networks:
      - ipbrick-v8
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    restart: always

volumes:
  database-data:
  keycloak_data:

networks:
  ipbrick-v8:
    driver: bridge

